### ISSUE TITLE
style 不支持scss预处理

### ISSUE THREAD

**Issue by Hack-DJ** [dream2023/vuepress-plugin-run#1]
如果vuepress-plugin-run能和vue-run-sfc一样支持css预处理就舒服了，不然写了组件还要改css才行

**Comment by dream2023** [comment]
支持的，需要在head中加入axios的cdn才行，参考：
https://github.com/dream2023/vue-run-sfc#%E9%A2%84%E5%A4%84%E7%90%86%E5%99%A8%E4%BD%BF%E7%94%A8

https://vuepress.vuejs.org/zh/config/#head
